# Generated by Django 2.0.3 on 2018-03-19 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
                ('houseNumber', models.CharField(max_length=50, null=True)),
                ('floor', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('fullName', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
                ('modelName', models.CharField(max_length=50, null=True)),
                ('ipAddress', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('contant', models.CharField(max_length=5000, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogPathTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('logPath', models.CharField(max_length=500, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
                ('portList', models.CharField(max_length=500, null=True)),
                ('logPathList', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OccupationTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('portNumber', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.CompanyTable')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.NodeTable')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.CompanyTable')),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.OccupationTable')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.CompanyTable')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
                ('contacts', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('website', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerRoomTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
                ('contacts', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('website', models.CharField(max_length=500, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.CompanyTable')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
                ('operationEngineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operationEngineer', to='cmdb1_demo1_app1.PrivateTable')),
                ('productManager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productManager', to='cmdb1_demo1_app1.PrivateTable')),
                ('programmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmer', to='cmdb1_demo1_app1.PrivateTable')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypeTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180319054121', max_length=49, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicetable',
            name='serviceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.ServiceTypeTable'),
        ),
        migrations.AddField(
            model_name='servicetable',
            name='softwareTestEngineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwareTestEngineer', to='cmdb1_demo1_app1.PrivateTable'),
        ),
        migrations.AddField(
            model_name='nodetable',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.ServiceTable'),
        ),
        migrations.AddField(
            model_name='logpathtable',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.NodeTable'),
        ),
    ]
