# Generated by Django 2.0.3 on 2018-08-25 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb1_demo1_app1', '0016_auto_20180825_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
                ('houseNumber', models.CharField(max_length=50, null=True)),
                ('floor', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeployHostTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeployLogTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.CharField(max_length=5000, null=True)),
                ('log', models.CharField(max_length=6587, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnviromentTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
                ('ipAddress', models.CharField(max_length=50, null=True)),
                ('controlPort', models.CharField(max_length=50, null=True)),
                ('sequence', models.CharField(max_length=50, null=True)),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.CabinetTable')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTypeTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('contant', models.CharField(max_length=5000, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogPathTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('logPath', models.CharField(max_length=500, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
                ('node', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeNumber', models.CharField(max_length=500, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
                ('portList', models.CharField(max_length=500, null=True)),
                ('logPathList', models.CharField(max_length=500, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
                ('springBootStartProfile', models.CharField(max_length=500, null=True)),
                ('memory', models.CharField(max_length=500, null=True)),
                ('enviroment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.EnviromentTable')),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.EquipmentTable')),
            ],
        ),
        migrations.CreateModel(
            name='OccupationTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('portNumber', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
                ('node', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
                ('contacts', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('website', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerRoomTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
                ('contacts', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('website', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
                ('javaVersion', models.CharField(max_length=50, null=True)),
                ('codeSrc', models.CharField(max_length=501, null=True)),
                ('mavenCodePath', models.CharField(max_length=500, null=True)),
                ('targetFilePath', models.CharField(max_length=500, null=True)),
                ('mavenParameter', models.CharField(max_length=500, null=True)),
                ('domainName', models.CharField(max_length=50, null=True)),
                ('nginxIp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.EquipmentTable')),
                ('operationEngineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operationEngineer', to='cmdb1_demo1_app1.PrivateTable')),
                ('productManager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productManager', to='cmdb1_demo1_app1.PrivateTable')),
                ('programmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmer', to='cmdb1_demo1_app1.PrivateTable')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='cmdb1_demo1_app1.ProjectTable')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypeTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('portNumber', models.CharField(default='20180825023335', max_length=49, null=True)),
                ('ctime', models.CharField(default='20180825023335', max_length=49, null=True)),
                ('logPathType', models.CharField(max_length=49, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='companytable',
            name='ctime',
            field=models.CharField(default='20180825023335', max_length=49, null=True),
        ),
        migrations.AddField(
            model_name='servicetable',
            name='serviceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.ServiceTypeTable'),
        ),
        migrations.AddField(
            model_name='servicetable',
            name='testEngineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwareTestEngineer', to='cmdb1_demo1_app1.PrivateTable'),
        ),
        migrations.AddField(
            model_name='serverroomtable',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.CompanyTable'),
        ),
        migrations.AddField(
            model_name='serverroomtable',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.ProviderTable'),
        ),
        migrations.AddField(
            model_name='projecttable',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.CompanyTable'),
        ),
        migrations.AddField(
            model_name='privatetable',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.CompanyTable'),
        ),
        migrations.AddField(
            model_name='privatetable',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.OccupationTable'),
        ),
        migrations.AddField(
            model_name='nodetable',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.ProjectTable'),
        ),
        migrations.AddField(
            model_name='nodetable',
            name='serverRoom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.ServerRoomTable'),
        ),
        migrations.AddField(
            model_name='nodetable',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.ServiceTable'),
        ),
        migrations.AddField(
            model_name='equipmenttable',
            name='equipmentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.EquipmentTypeTable'),
        ),
        migrations.AddField(
            model_name='equipmenttable',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.ProviderTable'),
        ),
        migrations.AddField(
            model_name='enviromenttable',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.CompanyTable'),
        ),
        migrations.AddField(
            model_name='deploylogtable',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.NodeTable'),
        ),
        migrations.AddField(
            model_name='deployhosttable',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.EquipmentTable'),
        ),
        migrations.AddField(
            model_name='deployhosttable',
            name='serverRoom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.ServerRoomTable'),
        ),
        migrations.AddField(
            model_name='cabinettable',
            name='serverRoom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb1_demo1_app1.ServerRoomTable'),
        ),
    ]
