# Generated by Django 2.0.3 on 2018-08-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('fullName', models.CharField(max_length=50, null=True)),
                ('uploadPath', models.CharField(max_length=50, null=True)),
                ('ctime', models.CharField(default='20180825023214', max_length=49, null=True)),
            ],
        ),
    ]
